/* Existing website wording and the biography supplied by the user are both retained. */
const originalContent={
  "homeHeading": "Turning dream homes into reality",
  "homeBio": "Working in real estate since 2015 provides Daisy with over six years of specialized experience. Between perfectly-staged homes and a deep understanding of how to earn the best possible gains, she has created immense returns for the communities she works within, – Irvine, Newport Beach, and Lake Forest. She specializes specifically in getting the highest return available on investments. Recently, she has made the highest selling record per square foot for each listing in the neighborhood, demonstrating her unmistakable expertise.",
  "about": [
    "Dedicated to her field, Daisy Li prides herself on prime negotiation, client-forward service, and ensuring the best result from an investment. A buyer’s agent, she has been called sincere and hardworking by her clients who value her work ethic, quick response times, comprehensive knowledge, trustworthiness, and honesty.",
    "Working in real estate since 2015 provides Daisy with over six years of specialized experience. Between perfectly-staged homes and a deep understanding of how to earn the best possible gains, she has created immense returns for the communities she works within, – Irvine, Newport Beach, and Lake Forest. She specializes specifically in getting the highest return available on investments. Recently, she has made the highest selling record per square foot for each listing in the neighborhood, demonstrating her unmistakable expertise.",
    "Valuing the community in the neighborhoods where she works, Daisy is passionate about volunteering at the local food bank, especially since COVID-19, in addition to aiding seniors with grocery shopping and other at-risk, necessary activities. Daisy loves to spend out-of-office hours with her husband, daughter, and son and pursuing her other passions, including piano, hiking, interior design, and portrait photography.",
    "After earning a bachelor’s degree in Education and then a master’s degree in International Journalism while living in London, Daisy worked as a program producer in a national TV channel and then as the founder of an outstanding design and marketing company. This long-term experience in leadership and commercial marketing roles has poised her to provide her clients with the best possible experience when it comes to the sometimes-challenging process of selling a property. This is especially prominent when considering the importance of ingenuity of art, design, staging, and creativity in marketing, all skills Daisy brings to the table.",
    "In addition to serving her communities, Daisy is also the principal broker in California of Seashine Property Service LLC, an affiliate of Seashine Capital Group. Seashine is a provider of REAL, the real estate lease acquisition program in ten major states. In April 2021, Atalaya Capital Management announced to join Seashine to invest up to $250 million dollars of its REAL Program assets."
  ],
  "chinese": [
    "Daisy Li加州最高经纪人broker执照, 是Seashine Realty 的创始人，也是获得华尔街2亿投资的的Seashine Property Service在加州的首席经纪人(Principal Broker)。",
    "Daisy Li以她的专业，细心，诚实，热情，时刻为客人着想的态度而被大家喜爱推荐。Daisy背后强大的团队支持，不管是房屋购买，房屋投资，房屋上市他们总能给客人提供超越他们期待的的服务。",
    "Daisy Li 拥有教育学学士和国际新闻硕士学位。在英国曾从事新闻行业，后回国在中央电视台CCTV英文频道参与一档全球新闻人物专访节目的制作。离开央视后曾创业5年，为CitiBank等全球跨国公司提供市场策略和创意设计服务。"
  ],
  "communities": {
    "irvine": {
      "heading": "Welcome to Irvine",
      "paragraphs": [
        "A lively city known for its focus on higher education",
        "Irvine has transformed over the century from sprawling, wide-open ranchland to a prosperous, diverse city that is\nhome to one of California’s best public universities. The population of Irvine is around 273,000 people. Its\nproximity to Los Angeles and the natural beauty of the Pacific coastline make Irvine a popular destination for\nSouthern Californians.\n\nIn the 19th century, James Irvine bought 110,000 acres of land that he used to create the Irvine Cattle Ranch.\nOver the years, the ranchland became an orchard for olives and the citrus trees that Orange County is known for.\n\nIn 1959, the sleepy, agricultural town of Irvine and Irvine Ranch underwent a significant transformation when the\nUniversity of California purchased land to build a campus there. In the decades since, Irvine has grown from a\nsleepy college town of around 50,000 to a lively, small city with plenty of opportunities, educational or\notherwise.\n\nIrvine is unique because it was planned to consist of smaller “villages” — neighborhoods throughout the city with\ntheir own distinct style, culture, and walkability. Some sought-after neighborhoods in the area are Orchard Hills,\nEastwood, Stonegate, Altair, Great Park, Turtle Rock.\n\nSince the city’s layout was carefully planned in the 1950s and ‘60s, neighborhoods are varied and walkable. The\narchitectural style in Irvine varies but boasts a large amount of midcentury California Modern style homes and\nMediterranean-style homes.\nThe median home price in Irvine is $861,600."
      ]
    },
    "newport-beach": {
      "heading": "Welcome to Newport Beach",
      "paragraphs": [
        "An affluent, seaside city with a thriving harbor",
        "Newport Beach is an affluent and bayside community in Orange County. The city is home to the largest recreational\nharbor on the West Coast, so there’s plenty to do in and around the sea.\n\nLong thought to be too dangerous for ships to pass, the Newport Bay remained virtually unexplored until the end of\nthe 19th century. In 1870, the first ship successfully docked in the new port — hence the name Newport.\n\nNewport Beach soon became a bustling community, and it was incorporated as a city in 1906. The growth was fueled\nby McFadden Wharf, a bustling wharf built in 1888 that was the largest business in Orange County at the time.\nNowadays, Newport Pier stands where McFadden Wharf once stood.\n\nDue to its maritime roots, Newport Beach is a popular spot for sailors of all kinds — whether their vessel of\nchoice is a humble fishing craft or a sleek and stylish sailboat.\n\nWhile land in the area went for $1 an acre in the late 19th century, the city is now affluent and desirable, with\na typical home price is around $2.6 million. The population of Newport Beach is 85,694."
      ]
    },
    "lake-forest": {
      "heading": "Welcome to Lake Forest",
      "paragraphs": [
        "A tight-knit community surrounded by eucalyptus groves",
        "Nestled within a eucalyptus grove and just a short drive from the sea, Lake Forest is a small and serene town in\nOrange County. It is situated southeast of the larger city of Irvine.\n\nOriginally ranchland, like much of the region, Lake Forest was home to a small community called El Toro. At the\nturn of the 20th century, a resident of El Toro named Dwight Whiting planted 400 acres of eucalyptus trees,\ncreating the forest that gives Lake Forest its name.\n\nIn the middle of the 20th century, residential development began within the eucalyptus forest, and the quiet\nagricultural town of El Toro started to grow. In 1991, the community was officially incorporated as a city, and\nthe name was changed from El Toro to Lake Forest to pay homage to the area’s natural beauty.\n\nLike its neighboring Orange County cities, Lake Forest was a master-planned community first developed in the\nmid-century. Because of this, it is well-designed and boasts a variety of homes, including single-family homes,\nluxury estates, condominiums, duplexes, and apartments.\n\nLake Forest has a range of architectural styles, including the mid-century classic California Modern style and the\nnewer Meditteranean style found in the Baker Ranch neighborhood. The median price of a home in Lake Forest is\napproximately $870,000, and the city’s population is around 87,000."
      ]
    },
    "coto-de-caza": {
      "heading": "Welcome to Coto de Caza",
      "paragraphs": [
        "A rural and serene master-planned community",
        "Coto de Caza is an affluent Census Designated Place in Orange County. Its luxurious estates have made a splash on\nthe silver screen twice — first in 1984 when the community was the center for the Olympics’ pentathlon events, and\nagain in the 21st century as the backdrop of the popular reality show, the Real Housewives of Orange County.\n\nLike many neighborhoods in Orange County, Coto de Caza comes from humble beginnings. Originally a barley ranch,\ndevelopment in the area began in the middle of the 20th century. Coto de Caza was originally a private hunting\nreserve and equestrian club — the name Coto de Caza is Spanish for “hunting preserve.”\n\nWith a population of 14,886, Coto de Caza has a close-knit sense of community. Residents enjoy the serenity and\nseclusion of the region — it’s easy to feel far from the hustle and bustle of urban life among Coto de Caza’s oak\nand sycamore groves.\n\nEver since its days as a hunting preserve, Coto de Caza has maintained a reputation of exclusivity and luxury. It\nhas fewer than 5,000 homes, all within its gates, so real estate is in high demand.\n\nThere are many different architectural styles in Coto de Caza, but especially Spanish Colonial, Meditteranean, and\nTuscan. The lots are known for being large and sprawling estates, and many have space for stables. The median home\nprice in Coto de Caza is around $2.9 million."
      ]
    }
  },
  "existingAbout": [
    "Dedicated to her field, Daisy Li prides herself on prime negotiation, client-forward service, and ensuring the best result from an investment. A buyer’s agent, she has been called sincere and hardworking by her clients who value her work ethic, quick response times, comprehensive knowledge, trustworthiness, and honesty.",
    "Working in real estate since 2015 provides Daisy with over six years of specialized experience. Between perfectly-staged homes and a deep understanding of how to earn the best possible gains, she’s created immense returns for the communities she works within,– Irvine, Newport Beach, and Lake Forest. She specializes specifically in getting the highest return available on investments. Recently, she has made the highest selling record per square foot for each listing in the neighborhood, demonstrating her unmistakable expertise.",
    "Valuing the community in the neighborhoods where she works, Daisy is passionate about volunteering at the local food bank, especially since COVID-19, in addition to aiding seniors with grocery shopping and other at-risk, necessary activities. Daisy loves to spend out-of-office hours with her husband, daughter, and son and pursuing her other passions, including piano, hiking, interior design, and portrait photography.",
    "After earning a bachelor’s degree in Education and then a master’s degree in International Journalism while living in London, Daisy worked as a program producer in a national TV channel and then as the founder of an outstanding design and marketing company. This long-term experience in leadership and commercial marketing roles has poised her to provide her clients with the best possible experience when it comes to the sometimes challenging process of selling a property. This is especially prominent when considering the importance of ingenuity of art, design, staging, and creativity in marketing, all skills Daisy brings to the table.",
    "In addition to serving her communities, Daisy is also the principal broker in California of Seashine Property Service LLC, an affiliate of Seashine Capital Group. Seashine is a provider of REAL, the real estate lease acquisition program in 10 major states. In April 2021, Atalaya Capital Management announced to join Seashine to invest up to 250 Million dollars of its REAL Program assets."
  ]
};
